=== Hjaltesorgenfrei/portalis/parseview/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "baseurl": {
      "pattern": "https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)",
      "type": "string"
    },
    "topRated": {
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "startPage": {"type": "integer"},
        "queryString": {
          "pattern": "{{pageNumber}}",
          "type": "string"
        }
      },
      "required": [
        "queryString",
        "startPage"
      ]
    },
    "$schema": {"type": "string"},
    "bookSelector": {
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "chapterDate": {"type": "string"},
        "chapter": {"type": "string"},
        "imageUri": {"type": "string"},
        "author": {"type": "string"},
        "chapterUri": {"type": "string"},
        "description": {"type": "string"},
        "chapterTitle": {"type": "string"},
        "title": {"type": "string"}
      },
      "required": [
        "author",
        "chapter",
        "chapterTitle",
        "chapterUri",
        "description",
        "imageUri",
        "title"
      ]
    },
    "overviewSelector": {
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "bookImageUri": {"type": "string"},
        "book": {"type": "string"},
        "bookUri": {"type": "string"},
        "bookTitle": {"type": "string"}
      },
      "required": [
        "book",
        "bookImageUri",
        "bookTitle",
        "bookUri"
      ]
    }
  },
  "required": [
    "baseurl",
    "bookSelector",
    "overviewSelector"
  ]
}

=== Hjaltesorgenfrei/portalis/parseview/royalroad.source.json
{
  "$schema": "./schema.json",
  "baseurl": "https://www.royalroad.com",
  "topRated":{
    "queryString": "/fictions/best-rated?page={{pageNumber}}",
    "startPage": 1
  },
  "overviewSelector": {
    "book": ".fiction-list-item.row",
    "bookTitle": ".fiction-title",
    "bookUri": "a[href]",
    "bookImageUri": "img[src]"
  },
  "bookSelector": {
    "title": ".fic-title h1",
    "author": ".fic-title h4 a",
    "description": ".description",
    "imageUri": "img.thumbnail[src]",
    "chapterTitle": "a",
    "chapter": ".chapter-row",
    "chapterDate": "time",
    "chapterUri": "a"
  }
}
